### ISSUE TITLE
Link from @pypa-bot and @Browntruck to this repository

### ISSUE THREAD

**Issue by pradyunsg** [pypa/browntruck#19]
For discoverability from those accounts.

/cc @techtonik

**Comment by pradyunsg** [comment]
@ewdurbin Maybe you have the permissions/access to do this?

**Comment by ewdurbin** [comment]
@pypa-bot is a user account. I'm not sure who controls/owns the account but it might be @dstufft?

**Comment by ewdurbin** [comment]
as is @BrownTruck.

**Comment by pradyunsg** [comment]
I got access. Let's see if I can fix these things.

**Comment by pradyunsg** [comment]
Done!
